@startuml Diagrama Cuidandonos

    class Transeunte{
        -nombreCompleto : String
        -direccion : String
        -edad : Integer
        -sexo : Sexo
        -trayectoAsociado : Trayecto
        -numeroDeTelefono : String
        -alertaConfigurada : Alerta

        +apretarBotonComenzarViaje() : void
        +apretarBotonLlegarBien() : void
        +quieroViajar(Ubicacion, Ubicacion, List<Cuidador>) : void
        +comenzarViaje() : void
        +ejecutarAlerta() : void
    }

    enum Sexo{
        FEMENINO,
        MASCULINO,
        OTRO
    }

    class Ubicacion{
        -latitud : String
        -longitud : String
    }

    class Cuidador{
        -trayectoAsociado : Trayecto

        +recibirNotificacion(String) : void
        +quiereHacerTrayecto() : boolean
    }

    class Trayecto{
        -transeunte : Transeunte
        -cuidadores : List<Cuidador>
        -inicio : Ubicacion
        -destino : Ubicacion

        +calcularDemora() : float
    }

    class Comenzado{}
    class FinalizadoCorrectamente{}
    class Solicitado{}


    interface Alerta{
        +alertar(Transeunte) : void
    }

    class AlertaACuidadores{
        +alertar(Transeunte) : void
    }

    class AlertaAPolicia{
        +alertar(Transeunte) : void
    }

    class Esperar{
        +alertar(Transeunte) : void
    }

    class LlamarACelular{
        +alertar(Transeunte) : void
    }

Transeunte --> Sexo
Trayecto --* Transeunte
Trayecto -->"*" Cuidador
Transeunte --> Ubicacion
Trayecto -->"*" Ubicacion
Transeunte ..> Alerta
AlertaACuidadores ..|> Alerta
AlertaAPolicia ..|> Alerta
Esperar ..|> Alerta
LlamarACelular ..|> Alerta
Comenzado --|> Trayecto
FinalizadoCorrectamente --|> Trayecto
Solicitado --|> Trayecto

@enduml