@startuml Diagrama Cuidandonos

    class Transeunte{
        -nombreCompleto : String
        -direccion : String
        -edad : Integer
        -sexo : Sexo
        -trayectoAsociado : Trayecto
        -numeroDeTelefono : String
        -alertaConfigurada : Alerta
        -trayectosRealizados : List<Trayecto>

        +apretarBotonComenzarViaje() : void
        +apretarBotonLlegarBien() : void
        +quieroViajar(Ubicacion, Ubicacion, List<Cuidador>) : void
        +comenzarViaje() : void
        +ejecutarAlerta() : void
    }

    enum Sexo{
        FEMENINO,
        MASCULINO,
        OTRO
    }

    class Ubicacion{
        -latitud : String
        -longitud : String
    }

    class Cuidador{
        -nombreCompleto : String
        -direccion : String
        -edad : Integer
        -sexo : Sexo
        -numeroDeTelefono : String
        -trayectoAsociado : Trayecto
        -trayectosRealizados : List<Trayecto>

        +recibirNotificacion(String) : void
        +quiereHacerTrayecto(Trayecto) : boolean
    }

    abstract class Trayecto{
        -transeunte : Transeunte
        -cuidadores : List<Cuidador>
        -inicio : Ubicacion
        -destino : Ubicacion
        -calculadoraDistancia : CalculadoraDistancia

        +calcularDemora() : float
        +cambiarEstado(Transeunte) : void
    }

    class Comenzado{
        +cambiarEstado(Transeunte) : void
    }
    class FinalizadoCorrectamente{
        +cambiarEstado(Transeunte) : void
    }
    class Solicitado{
        +cambiarEstado(Transeunte) : void
    }

    interface CalculadoraDistancia{
        +calcularDistancia(Ubicacion, Ubicacion) : float
    }

    class DistanciaMatrixAPI{
        +calcularDistancia(Ubicacion, Ubicacion) : float
    }

    interface Alerta{
        +alertar(Transeunte) : void
    }

    class AlertaACuidadores{
        +alertar(Transeunte) : void
    }

    class AlertaAPolicia{
        +alertar(Transeunte) : void
    }

    class Esperar{
        +alertar(Transeunte) : void
    }

    class LlamarACelular{
        +alertar(Transeunte) : void
    }

Transeunte --> Sexo
Trayecto --* Transeunte
Trayecto -->"*" Cuidador
Transeunte --> Ubicacion
Trayecto -->"*" Ubicacion
Transeunte ..> Alerta
AlertaACuidadores ..|> Alerta
AlertaAPolicia ..|> Alerta
Esperar ..|> Alerta
LlamarACelular ..|> Alerta
Comenzado --|> Trayecto
FinalizadoCorrectamente --|> Trayecto
Solicitado --|> Trayecto
DistanciaMatrixAPI ..|> CalculadoraDistancia
Trayecto ..> CalculadoraDistancia

@enduml